#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

#
# disable getty on tty1 to quiten down the console if
# the "nogetty" keyword is set in cmdline.txt
#
SYSTEMDDIR="/root/writable/system-data/etc/systemd"
JOBDIR="${SYSTEMDDIR}/system"

if ! grep -q " nogetty " /proc/cmdline; then
	SVCFILE="${JOBDIR}/getty.target.wants/getty@tty1.service"
	ln -s /lib/systemd/system/getty@.service $SVCFILE || true
else
	rm -f "${JOBDIR}/getty.target.wants/getty@tty"?".service" || true
fi

SERVICENAME="end.psplash.service"
if [ ! -e "${JOBDIR}/${SERVICENAME}" ]; then
	cp "/scripts/init-bottom/${SERVICENAME}" "${JOBDIR}/${SERVICENAME}"
	ln -s "/etc/systemd/system/${SERVICENAME}" "${JOBDIR}/multi-user.target.wants/${SERVICENAME}"
fi

# HACK to work around missing support for "connections:" in gadget.yaml
# in ubuntu-image currently ... once this is fixed we can drop the hack
#SERVICENAME="kiosk.autoconnect.service"
#if [ ! -e "${JOBDIR}/${SERVICENAME}" ]; then
#	cp "/scripts/init-bottom/${SERVICENAME}" "${JOBDIR}/${SERVICENAME}"
#	ln -s "/etc/systemd/system/${SERVICENAME}" "${JOBDIR}/multi-user.target.wants/${SERVICENAME}"
#fi


